<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap | Kumocode</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
						font-size: 14px;
						color: #333;
						margin: 0;
						padding: 40px 20px;
						background-color: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 40px;
						border-radius: 12px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					h1 {
						color: #0f172a;
						font-size: 24px;
						margin-top: 0;
						margin-bottom: 10px;
						display: flex;
						align-items: center;
						gap: 10px;
					}
					p {
						color: #64748b;
						margin-bottom: 30px;
						line-height: 1.5;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 12px 15px;
						border-bottom: 2px solid #e2e8f0;
						color: #475569;
						font-weight: 600;
						text-transform: uppercase;
						font-size: 11px;
						letter-spacing: 0.05em;
					}
					td {
						padding: 12px 15px;
						border-bottom: 1px solid #f1f5f9;
						word-break: break-all;
					}
					tr:hover td {
						background-color: #f8fafc;
					}
					a {
						color: #2563eb;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.priority-high { color: #16a34a; font-weight: 600; }
					.priority-mid { color: #ea580c; }
					.priority-low { color: #94a3b8; }
					.footer {
						margin-top: 40px;
						text-align: center;
						color: #94a3b8;
						font-size: 12px;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>
						This XML Sitemap is generated by Kumocode to help search engines like Google and Bing discover your content more efficiently. 
						It contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
					</p>
					<table>
						<thead>
							<tr>
								<th>URL</th>
								<th>Priority</th>
								<th>Change Freq</th>
								<th>Last Modified</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="sitemap:urlset/sitemap:url">
								<tr>
									<td>
										<xsl:variable name="itemURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<a href="{$itemURL}">
											<xsl:value-of select="sitemap:loc"/>
										</a>
									</td>
									<td>
										<xsl:choose>
											<xsl:when test="sitemap:priority &gt; 0.8">
												<span class="priority-high"><xsl:value-of select="sitemap:priority"/></span>
											</xsl:when>
											<xsl:when test="sitemap:priority &gt; 0.5">
												<span class="priority-mid"><xsl:value-of select="sitemap:priority"/></span>
											</xsl:when>
											<xsl:otherwise>
												<span class="priority-low"><xsl:value-of select="sitemap:priority"/></span>
											</xsl:otherwise>
										</xsl:choose>
									</td>
									<td>
										<xsl:value-of select="sitemap:changefreq"/>
									</td>
									<td>
										<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
									</td>
								</tr>
							</xsl:for-each>
						</tbody>
					</table>
				</div>
				<div class="footer">
					Built with ❤️ by <a href="https://kumocode.co.za">Kumocode</a>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
